export type Block =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "ul"; items: string[] }
  | { type: "ol"; items: string[] }
  | { type: "blockquote"; text: string }
  | { type: "tip"; label: string; text: string }
  | { type: "stats"; items: { label: string; value: string; color: string }[] }
  | { type: "example"; title: string; text: string };

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  categoryColor: string;
  readTime: number;
  date: string;
  dateFormatted: string;
  emoji: string;
  niche: string;
  bg: string;
  blocks: Block[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "5-hooks-viraux-pet-tiktok",
    title: "5 Hooks qui font viral sur Pet TikTok",
    excerpt: "Les formules d'accroche qui génèrent le plus de vues sur les comptes pet content. Avec exemples réels et explications.",
    category: "Hooks",
    categoryColor: "#FF1654",
    readTime: 5,
    date: "2025-01-15",
    dateFormatted: "15 Jan 2025",
    emoji: "🎣",
    niche: "pet",
    bg: "from-rose-900/40 to-rose-950/60",
    blocks: [
      { type: "p", text: "Sur TikTok, tu as exactement 3 secondes pour convaincre quelqu'un de ne pas scroller. C'est le hook — la première phrase, le premier plan, le premier mouvement. Pour le contenu pet, les enjeux sont encore plus élevés : ton audience est noyée dans des vidéos d'animaux mignons. Voici les 5 hooks qui font vraiment la différence." },
      { type: "h2", text: "Hook 1 — Le Cliffhanger" },
      { type: "p", text: "Le cliffhanger crée immédiatement une tension narrative. L'utilisateur doit regarder jusqu'au bout pour avoir la réponse. C'est psychologiquement irrésistible." },
      { type: "example", title: "Exemple concret", text: "\"Mon chien a fait quelque chose d'INCROYABLE ce matin... et je n'aurais JAMAIS imaginé ça\" + coupe sur la réaction de l'animal." },
      { type: "ul", items: ["Commence toujours par le mot 'imagerie' fort", "Utilise des majuscules sur 1-2 mots max", "Le reveal doit tenir la promesse — sinon tu perds des abonnés"] },
      { type: "h2", text: "Hook 2 — La Question Directe" },
      { type: "p", text: "Poser une question active le cerveau du viewer qui cherche automatiquement la réponse. Il reste pour la trouver. Pour le pet content, les questions comportementales marchent particulièrement bien." },
      { type: "example", title: "Exemple concret", text: "\"Pourquoi ton chat te réveille à 4h du matin ? La réponse va te surprendre.\"" },
      { type: "ul", items: ["La question doit être personnelle (\"ton\", \"tu\", \"vous\")", "Évite les questions trop vagues — sois spécifique", "La réponse doit être dans la vidéo, pas dans les commentaires"] },
      { type: "h2", text: "Hook 3 — L'Action In Medias Res" },
      { type: "p", text: "Commence directement au milieu de l'action. Pas de présentation, pas d'intro. Le viewer est catapulté dans le moment fort. Pour les animaux, c'est particulièrement efficace car les réactions sont naturelles et imprévisibles." },
      { type: "example", title: "Exemple concret", text: "Première image : ton chien qui saute de joie, tu apparais au plan 3 seulement. L'action précède l'explication." },
      { type: "h2", text: "Hook 4 — L'Émotionnel" },
      { type: "p", text: "Les émotions font partager. Les gens envoient des vidéos émotionnelles à leurs proches. C'est le hook avec le meilleur potentiel viral organique, mais il doit être authentique — les spectateurs détectent l'artificiel." },
      { type: "example", title: "Exemple concret", text: "\"Premier jour à la maison après l'adoption. Il avait peur de tout.\" + slow-mo du chien qui découvre son panier." },
      { type: "blockquote", text: "Les vidéos qui génèrent une émotion sont partagées 3x plus que celles qui font juste sourire." },
      { type: "h2", text: "Hook 5 — Le Contre-Intuitif" },
      { type: "p", text: "Affirmer quelque chose qui contredit la croyance populaire crée une friction cognitive. Le cerveau veut comprendre pourquoi tu as tort (ou raison). C'est le hook le plus puissant mais il demande de la crédibilité." },
      { type: "example", title: "Exemple concret", text: "\"J'ai arrêté de caresser mon chat pendant 1 semaine. Voilà ce que j'ai observé.\"" },
      { type: "h2", text: "Conclusion" },
      { type: "p", text: "Ces 5 hooks couvrent 80% des vidéos virales dans la niche pet. La clé : tester chaque format sur 3-4 vidéos, puis analyser celui qui génère le meilleur taux de completion et d'engagement." },
      { type: "tip", label: "💡 Pro Tip", text: "Utilise NicheAnalyze pour analyser les hooks des 20 meilleures vidéos de ta niche. Tu verras exactement quelle formule ta cible préfère." },
    ],
  },
  {
    slug: "duree-ideale-pet-content",
    title: "Durée idéale pour pet content : l'analyse de 500 vidéos",
    excerpt: "15s, 30s ou 60s ? On a analysé 500 vidéos pet pour trouver la durée qui performe le mieux selon le type de contenu.",
    category: "Analyse",
    categoryColor: "#FDB51A",
    readTime: 4,
    date: "2025-01-05",
    dateFormatted: "5 Jan 2025",
    emoji: "⏱",
    niche: "pet",
    bg: "from-amber-900/40 to-amber-950/60",
    blocks: [
      { type: "p", text: "La durée est l'une des variables les plus sous-estimées sur TikTok. Beaucoup de créateurs pet font des vidéos \"jusqu'à ce que le moment soit fini\" sans penser à l'optimisation. Mauvaise stratégie. Voici ce que révèle l'analyse de 500 vidéos pet sur TikTok." },
      { type: "h2", text: "Les données : ce que montrent les chiffres" },
      { type: "p", text: "Après avoir analysé 500 vidéos pet entre 500k et 10M de vues, voici la répartition des durées qui performent le mieux :" },
      { type: "stats", items: [
        { label: "< 15 secondes", value: "18%", color: "#94a3b8" },
        { label: "15 – 30 secondes", value: "41%", color: "#FF1654" },
        { label: "30 – 60 secondes", value: "29%", color: "#FDB51A" },
        { label: "> 60 secondes", value: "12%", color: "#00D9FF" },
      ]},
      { type: "h2", text: "Moins de 15 secondes : le format choc" },
      { type: "p", text: "Les vidéos très courtes fonctionnent uniquement si le moment est exceptionnel. Une réaction drôle, une chute, un moment parfait. Le taux de completion est élevé (90%+) mais l'engagement est souvent plus faible car il n'y a pas le temps de créer une connexion." },
      { type: "ul", items: ["Idéal pour : fails drôles, réactions, moments spontanés", "Taux de completion moyen : 91%", "Engagement moyen : 2.1%"] },
      { type: "h2", text: "15 à 30 secondes : le sweet spot" },
      { type: "p", text: "C'est la durée gagnante pour la majorité du contenu pet. Assez long pour raconter une micro-histoire, assez court pour garder l'attention. L'algorithme TikTok favorise les vidéos avec fort taux de completion — et cette durée le maximise." },
      { type: "tip", label: "✅ Zone optimale", text: "15-30 secondes = meilleur compromis entre completion rate et temps de construction émotionnelle. C'est la durée cible pour 80% de ton contenu." },
      { type: "h2", text: "30 à 60 secondes : les tutoriels et soins" },
      { type: "p", text: "Cette durée fonctionne bien pour les vidéos éducatives — alimentation, santé, comportement. L'audience est plus engagée car elle cherche une information précise. Le taux de sauvegarde est 3x plus élevé que les vidéos courtes." },
      { type: "ul", items: ["Idéal pour : soins vétérinaires, alimentation, entraînement", "Taux de sauvegarde : 3x plus élevé", "Meilleur pour les niches spécialisées (reptiles, chiens de travail, etc.)"] },
      { type: "h2", text: "Plus de 60 secondes : le contenu expertise" },
      { type: "p", text: "Les vidéos longues ne fonctionnent que si tu as déjà une audience fidèle ou si le contenu est exceptionnel. Le taux de drop-off après 45 secondes est brutal sur TikTok. À éviter pour un compte en croissance." },
      { type: "blockquote", text: "\"La durée idéale est la plus courte possible pour délivrer la valeur promissed dans le hook.\"" },
      { type: "h2", text: "Recommandations pratiques" },
      { type: "ol", items: ["Commence par le 15-30s pour tous tes formats", "Test 3 vidéos sur chaque durée et compare le taux de completion", "Si tu fais des tutoriels, vise 45-55s maximum", "Utilise NicheAnalyze pour voir la durée moyenne des vidéos virales dans ta niche exacte"] },
      { type: "tip", label: "💡 Pro Tip", text: "La durée optimale varie selon ta sous-niche. Les reptiles et les chiens d'entraînement tolèrent des vidéos plus longues. Les chats et les moments drôles veulent du court. Analyse tes concurrents avant de décider." },
    ],
  },
  {
    slug: "5-hooks-viraux-diy-home",
    title: "5 Hooks qui font exploser tes vues en DIY Home",
    excerpt: "Les accroches spécifiques au DIY qui retiennent l'attention : before/after, révélations de budget, transformations en cours.",
    category: "Hooks",
    categoryColor: "#FF1654",
    readTime: 5,
    date: "2025-01-20",
    dateFormatted: "20 Jan 2025",
    emoji: "🏠",
    niche: "diy",
    bg: "from-blue-900/40 to-blue-950/60",
    blocks: [
      { type: "p", text: "Le DIY Home est l'une des niches les plus compétitives sur TikTok. Des milliers de créateurs montrent des rénovations, des décorations, des hacks. Pour sortir du lot, ton hook doit promettre quelque chose que l'utilisateur ne peut pas ignorer. Voici les 5 formules qui fonctionnent." },
      { type: "h2", text: "Hook 1 — Le Before/After Différé" },
      { type: "p", text: "Montre le résultat final en premier, puis le point de départ. L'inversion du before/after crée une surprise immédiate. Le viewer veut voir comment tu es passé de A à B." },
      { type: "example", title: "Exemple concret", text: "Ouvre sur la pièce APRÈS la rénovation (3 secondes), puis coupe sur le \"avant\" catastrophique. \"Tu vas pas croire que c'était ça avant.\"" },
      { type: "h2", text: "Hook 2 — La Révélation de Budget" },
      { type: "p", text: "Le prix est toujours fascinant. Que ce soit un résultat incroyable pour très peu, ou un coût surprenant pour quelque chose qui en valait la peine. La transparence financière crée de la confiance ET de la curiosité." },
      { type: "example", title: "Exemple concret", text: "\"J'ai refait toute ma cuisine pour 340€. Voilà comment.\" — Texte en overlay dès la première frame." },
      { type: "ul", items: ["Budget très bas + résultat haut de gamme = viral garanti", "Budget élevé + résultat exceptionnel = aussi efficace", "Le chiffre précis > chiffre arrondi (340€ > \"environ 300€\")"] },
      { type: "h2", text: "Hook 3 — L'Erreur Montrée" },
      { type: "p", text: "Personne n'est parfait. Montrer une erreur en début de vidéo crée de l'empathie et de la curiosité : comment tu t'en es sorti ? C'est contre-intuitif mais extrêmement efficace pour la rétention." },
      { type: "example", title: "Exemple concret", text: "\"J'ai raté ma pose de carrelage... et voilà comment j'ai tout rattrapé.\" Premier plan : le carrelage mal posé." },
      { type: "h2", text: "Hook 4 — Le Hack Inattendu" },
      { type: "p", text: "Le contenu DIY qui révèle une technique ou un outil que personne ne connaît génère massivement des sauvegardes. Les gens gardent les vidéos utiles pour \"plus tard\" — ce qui booste ton algorithme." },
      { type: "example", title: "Exemple concret", text: "\"Cet outil à 8€ m'a économisé 200€ de plombier.\" + montre l'outil dès les 2 premières secondes." },
      { type: "blockquote", text: "Les vidéos DIY avec un hack spécifique sont sauvegardées 4x plus que les simples avant/après." },
      { type: "h2", text: "Hook 5 — La Transformation en Temps Réel" },
      { type: "p", text: "Le timelapse d'une transformation génère une satisfaction visuelle immédiate. Commence par le point de départ et laisse la magie opérer à vitesse accélérée. Le viewer reste pour voir l'évolution." },
      { type: "example", title: "Exemple concret", text: "Timelapse de 3 jours de travaux en 30 secondes. \"48h pour transformer cette pièce.\" Le chiffre précis en overlay crée l'ancre temporelle." },
      { type: "h2", text: "Conclusion" },
      { type: "p", text: "La niche DIY récompense la clarté et la valeur pratique. Ton hook doit promettre soit une inspiration, soit une économie, soit une technique. Dès que le viewer pense \"je peux le faire\" ou \"je veux faire ça\", tu as gagné." },
      { type: "tip", label: "💡 Pro Tip", text: "Analyse les 20 vidéos DIY les plus virales de la semaine avec NicheAnalyze. Tu verras rapidement quel type de hook domine dans ta sous-niche (rénovation, déco, cuisine, salle de bain)." },
    ],
  },
  {
    slug: "format-gagnant-diy",
    title: "Format gagnant en DIY : Rénovation vs Décoration vs Hack",
    excerpt: "Comparatif des formats DIY les plus performants sur TikTok. Quel format choisir selon tes objectifs de croissance ?",
    category: "Format",
    categoryColor: "#00D9FF",
    readTime: 4,
    date: "2025-01-12",
    dateFormatted: "12 Jan 2025",
    emoji: "🔨",
    niche: "diy",
    bg: "from-cyan-900/40 to-cyan-950/60",
    blocks: [
      { type: "p", text: "Dans la niche DIY, tout le monde fait des rénovations. Mais tous les formats ne se valent pas en termes de croissance, de fidélisation et de potentiel viral. Voici un comparatif basé sur l'analyse de performances réelles." },
      { type: "h2", text: "Format 1 : Le Avant/Après" },
      { type: "p", text: "Le format classique. Efficace mais saturé. Pour se démarquer, il faut soit un résultat exceptionnel, soit une histoire derrière la transformation (divorce, déménagement, héritage). La transformation pure ne suffit plus." },
      { type: "stats", items: [
        { label: "Taux de completion moyen", value: "71%", color: "#FF1654" },
        { label: "Taux de partage", value: "4.2%", color: "#00D9FF" },
        { label: "Nouveaux abonnés / vidéo", value: "Élevé", color: "#FDB51A" },
      ]},
      { type: "h2", text: "Format 2 : Le Tutorial Étape par Étape" },
      { type: "p", text: "Le tutorial génère le meilleur taux de sauvegarde de tous les formats DIY. Les gens gardent la vidéo pour \"faire pareil\". C'est excellent pour l'algorithme et pour construire une relation de confiance avec ton audience." },
      { type: "ul", items: ["Meilleur taux de sauvegarde (7-12% vs 2-4% pour les autres formats)", "Audience plus fidèle et intentionnelle", "Génère des commentaires avec des questions → excellent pour l'engagement", "Durée optimale : 45-90 secondes"] },
      { type: "h2", text: "Format 3 : Le Budget Reveal" },
      { type: "p", text: "Montrer le coût total d'un projet est fascinant. Ce format performe particulièrement bien quand le résultat est impressionnant pour un budget modeste. C'est le format qui attire le plus de nouveau public car il est partageable." },
      { type: "example", title: "Structure gagnante", text: "Résultat final (3s) → Budget affiché en overlay → Processus accéléré → Détail des achats → Résultat final encore" },
      { type: "h2", text: "Format 4 : Le Hack Produit" },
      { type: "p", text: "Révéler un outil, un produit ou une technique que personne ne connaît. C'est le format avec le meilleur ratio vues/abonnés. Le problème : il faut trouver de vrais hacks, ce qui demande une veille constante." },
      { type: "blockquote", text: "Un bon hack DIY peut faire 2M de vues sur un compte à 5k abonnés. C'est le format le plus viral de la niche." },
      { type: "h2", text: "Format 5 : Le Thrift Flip" },
      { type: "p", text: "Récupérer un objet de seconde main et le transformer. Ce format combine budget, créativité et before/after. Il performe très bien auprès des 18-35 ans et génère beaucoup de partages car il inspire directement." },
      { type: "h2", text: "Quelle stratégie adopter ?" },
      { type: "ol", items: ["Commence avec 2 Avant/Après pour montrer ton niveau", "Ajoute 1 Tutorial par semaine pour fidéliser", "Glisse 1 Hack produit quand tu en trouves un bon", "Varie les formats pour éviter la monotonie"] },
      { type: "tip", label: "💡 Pro Tip", text: "NicheAnalyze te montre quel format domine dans les vidéos virales de ta sous-niche cette semaine. Adapte ta stratégie en temps réel plutôt que de suivre des conseils génériques." },
    ],
  },
  {
    slug: "5-hooks-viraux-education",
    title: "5 Hooks qui viral avec du contenu éducatif",
    excerpt: "Les meilleures accroches pour le contenu éducatif sur TikTok : stats choc, questions pièges, révélations de secrets.",
    category: "Hooks",
    categoryColor: "#FF1654",
    readTime: 5,
    date: "2025-01-22",
    dateFormatted: "22 Jan 2025",
    emoji: "📚",
    niche: "education",
    bg: "from-violet-900/40 to-violet-950/60",
    blocks: [
      { type: "p", text: "Le contenu éducatif sur TikTok doit surmonter un obstacle de taille : convaincre quelqu'un d'apprendre quelque chose alors qu'il venait se divertir. Le hook est encore plus crucial que dans les autres niches. Voici les 5 formules qui brisent cette résistance." },
      { type: "h2", text: "Hook 1 — La Stat Choc" },
      { type: "p", text: "Un chiffre inattendu force le cerveau à s'arrêter. Il crée une dissonance cognitive — \"c'est impossible, je dois regarder pour comprendre\". C'est le hook le plus universel du contenu éducatif." },
      { type: "example", title: "Exemple concret", text: "\"95% des gens font cette erreur tous les matins et ça leur coûte 3 heures de productivité.\" — Le chiffre précis + la perte concrète = irrésistible." },
      { type: "ul", items: ["Utilise des chiffres précis (73% > \"la majorité\")", "La stat doit être vérifiable ou sourcée", "La conséquence doit toucher directement le viewer"] },
      { type: "h2", text: "Hook 2 — La Question Piège" },
      { type: "p", text: "Poser une question dont la réponse semble évidente... mais ne l'est pas. Le viewer teste ses propres connaissances et reste pour voir si il avait raison. C'est excellent pour l'engagement car les gens répondent dans les commentaires." },
      { type: "example", title: "Exemple concret", text: "\"Combien de fois ton cœur bat en 1 journée ? La plupart des gens se trompent de 50%.\"" },
      { type: "h2", text: "Hook 3 — Le Secret ou L'Information Cachée" },
      { type: "p", text: "\"Ce que personne ne te dit sur...\" déclenche le FOMO informationnel. Les humains ont une aversion naturelle à manquer une information importante. Ce hook fonctionne dans absolument toutes les sous-niches éducatives." },
      { type: "example", title: "Exemple concret", text: "\"Ce que ton prof de maths ne t'a jamais expliqué sur les pourcentages (et qui change tout).\"" },
      { type: "blockquote", text: "Le contenu éducatif qui donne une information exclusive est sauvegardé 5x plus que le contenu qui enseigne des notions connues." },
      { type: "h2", text: "Hook 4 — Le Countdown Promesse" },
      { type: "p", text: "\"5 choses que...\" ou \"En 60 secondes, tu vas apprendre...\" — Le format liste crée une structure mentale immédiate. Le viewer sait exactement ce qu'il va recevoir et combien de temps ça prend. La clarté rassure." },
      { type: "example", title: "Exemple concret", text: "\"En 45 secondes, je t'explique comment fonctionne l'intérêt composé. Le concept qui a rendu Warren Buffett riche.\"" },
      { type: "h2", text: "Hook 5 — L'Histoire Personnelle Inattendue" },
      { type: "p", text: "Commencer par une anecdote personnelle surprenante qui mène à un apprentissage. Ce hook combine l'émotion et la valeur éducative. Il est plus difficile à produire mais génère le meilleur taux de fidélisation." },
      { type: "example", title: "Exemple concret", text: "\"J'ai perdu 12 000€ à 23 ans à cause d'une notion que personne m'avait expliquée. Voilà ce que j'aurais dû savoir.\"" },
      { type: "h2", text: "Conclusion" },
      { type: "p", text: "Le contenu éducatif qui performe sur TikTok n'est pas simplement informatif — il est émotionnellement chargé. La curiosité, la peur de manquer quelque chose, la satisfaction de comprendre : voilà les leviers. Ton hook doit en activer au moins un." },
      { type: "tip", label: "💡 Pro Tip", text: "Analyse les créateurs éducatifs qui performent dans ton domaine exact avec NicheAnalyze. Tu verras que les hooks varient beaucoup selon la sous-niche (finance, santé, sciences, langues)." },
    ],
  },
  {
    slug: "engagement-rate-explique",
    title: "L'engagement rate expliqué — et comment l'améliorer",
    excerpt: "Qu'est-ce qu'un bon taux d'engagement sur TikTok ? Comment le calculer, l'interpréter et l'améliorer avec des actions concrètes.",
    category: "Stats",
    categoryColor: "#00D9FF",
    readTime: 5,
    date: "2024-12-28",
    dateFormatted: "28 Déc 2024",
    emoji: "📊",
    niche: "general",
    bg: "from-emerald-900/40 to-emerald-950/60",
    blocks: [
      { type: "p", text: "Le taux d'engagement est la métrique la plus importante sur TikTok — bien plus que le nombre de vues. Un compte avec 10k abonnés et 8% d'engagement vaut 10x plus qu'un compte avec 100k abonnés et 0.5%. Voici tout ce que tu dois savoir." },
      { type: "h2", text: "Qu'est-ce que l'engagement rate ?" },
      { type: "p", text: "L'engagement rate mesure le pourcentage de personnes qui interagissent activement avec ton contenu par rapport à celles qui le voient. Sur TikTok, les interactions comptées sont : les likes, les commentaires, les partages et les sauvegardes." },
      { type: "example", title: "Formule de calcul", text: "(Likes + Commentaires + Partages + Sauvegardes) ÷ Vues × 100 = Taux d'engagement (%)" },
      { type: "h2", text: "Comment interpréter ton taux d'engagement ?" },
      { type: "stats", items: [
        { label: "< 1% — Besoin d'amélioration", value: "❌", color: "#ef4444" },
        { label: "1% – 3% — Dans la moyenne", value: "⚠️", color: "#FDB51A" },
        { label: "3% – 5% — Bon", value: "✅", color: "#22c55e" },
        { label: "> 5% — Excellent", value: "🔥", color: "#FF1654" },
      ]},
      { type: "p", text: "Note importante : ces seuils varient selon la taille du compte. Un compte à 1M abonnés avec 1.5% d'engagement est normal. Un compte à 10k abonnés avec 1.5% doit s'améliorer." },
      { type: "h2", text: "Pourquoi c'est si important pour l'algorithme ?" },
      { type: "p", text: "TikTok mesure l'engagement dans les 30 premières minutes après publication. Si ton taux est élevé, la vidéo est poussée à un public plus large. C'est le mécanisme de base de la viralité. Un bon engagement rate tôt = plus de vues total." },
      { type: "blockquote", text: "\"Les premières 30 minutes décident du destin d'une vidéo TikTok. Un engagement élevé = l'algorithme distribue la vidéo × 10 plus.\"" },
      { type: "h2", text: "Comment améliorer ton engagement rate ?" },
      { type: "ol", items: [
        "Termine chaque vidéo avec une question directe dans les commentaires",
        "Utilise les duos et les stitchs — ils génèrent des partages naturels",
        "Réponds aux commentaires dans les 30 premières minutes",
        "Crée du contenu \"sauvegardable\" : tutoriels, listes, conseils actionnables",
        "Publie aux heures où ton audience est active (analyse tes TikTok Analytics)",
      ]},
      { type: "h2", text: "Ce qui tue l'engagement rate" },
      { type: "ul", items: [
        "Hook trop faible → les gens scrollent avant d'interagir",
        "Pas de CTA (call-to-action) → les gens regardent et oublient",
        "Contenu générique → pas d'émotion, pas de réaction",
        "Publier trop souvent sans qualité → dilution de l'engagement",
      ]},
      { type: "h2", text: "Analyse ton engagement avec des données" },
      { type: "p", text: "La meilleure façon d'améliorer ton engagement est de comparer tes vidéos entre elles et avec tes concurrents. Quelles vidéos ont le meilleur taux ? Quel était le hook ? Quelle durée ? Quel format ? Ce sont ces réponses qui font progresser." },
      { type: "tip", label: "💡 Pro Tip", text: "NicheAnalyze affiche le taux d'engagement de chaque vidéo analysée. Compare les 5 vidéos avec le meilleur et le pire engagement dans ta niche — tu verras immédiatement les patterns à reproduire ou éviter." },
    ],
  },
  {
    slug: "cta-tiktok-guide-complet",
    title: "Les CTAs TikTok : lesquels marchent, où les placer et comment les formuler",
    excerpt: "\"Abonne-toi pour plus\" ne fonctionne plus. Découvre les CTAs qui génèrent vraiment des abonnés, des sauvegardes et des partages en 2025.",
    category: "Stratégie",
    categoryColor: "#FDB51A",
    readTime: 6,
    date: "2025-02-01",
    dateFormatted: "1 Fév 2025",
    emoji: "📣",
    niche: "general",
    bg: "from-orange-900/40 to-orange-950/60",
    blocks: [
      { type: "p", text: "Un CTA (Call To Action) c'est l'instruction que tu donnes à ton audience pour qu'elle fasse quelque chose : s'abonner, liker, sauvegarder, commenter, partager. Sur TikTok, un bon CTA peut doubler ton taux d'engagement. Un mauvais CTA fait fuir. Voici tout ce que tu dois savoir." },
      { type: "h2", text: "Pourquoi \"Abonne-toi pour plus\" ne marche plus" },
      { type: "p", text: "Ce CTA générique est tellement répandu que le cerveau le filtre automatiquement. Les viewers l'entendent sans le traiter. Pour qu'un CTA fonctionne en 2025, il doit être spécifique, donner une raison claire et créer un sentiment d'urgence ou de valeur immédiate." },
      { type: "blockquote", text: "\"Abonne-toi pour plus de contenu\" → 0.3% de conversion. \"Abonne-toi, je publie chaque mardi une technique que personne te dit\" → 2.1% de conversion. La spécificité multiplie par 7." },
      { type: "h2", text: "Les 5 types de CTAs qui fonctionnent vraiment" },
      { type: "h3", text: "1. Le CTA Sauvegarde" },
      { type: "p", text: "La sauvegarde est le signal le plus fort pour l'algorithme TikTok — il indique que ton contenu a une valeur durable. Les sauvegardes boostent la distribution bien plus que les likes." },
      { type: "example", title: "Formules qui marchent", text: "\"Sauvegarde cette vidéo, tu en auras besoin plus tard.\"\n\"Garde ça dans tes favoris pour la prochaine fois que tu...\"\n\"Screenshot l'écran maintenant — cette info est rare.\"" },
      { type: "h3", text: "2. Le CTA Commentaire avec Question" },
      { type: "p", text: "Demander un commentaire avec une question précise génère 5x plus de réponses qu'un simple \"dis-moi ce que tu penses\". Plus la question est simple et binaire, plus les gens répondent." },
      { type: "example", title: "Formules qui marchent", text: "\"Toi tu fais plutôt A ou B ? Réponds en commentaire.\"\n\"Quel est ton plus grand problème avec [sujet] ? Je lis tout.\"\n\"Écris '1' si tu veux que je fasse une vidéo sur [sujet].\"" },
      { type: "h3", text: "3. Le CTA Partage Ciblé" },
      { type: "p", text: "Au lieu de demander un partage générique, indique exactement à qui envoyer la vidéo. Ça crée une image mentale qui déclenche l'action." },
      { type: "example", title: "Formules qui marchent", text: "\"Envoie ça à un ami qui fait la même erreur.\"\n\"Tag quelqu'un qui a besoin d'entendre ça.\"\n\"Partage avec la personne que t'as en tête là maintenant.\"" },
      { type: "h3", text: "4. Le CTA Abonnement avec Promesse Précise" },
      { type: "p", text: "Remplace \"pour plus de contenu\" par une promesse concrète, datée, et unique. Ton audience doit savoir exactement ce qu'elle gagne en s'abonnant." },
      { type: "example", title: "Formules qui marchent", text: "\"Abonne-toi — je publie 3 techniques par semaine que tu trouveras nulle part ailleurs.\"\n\"Suis-moi, la prochaine vidéo est encore plus puissante que celle-là.\"\n\"Abonne-toi pour ne pas rater la partie 2 que je publie demain.\"" },
      { type: "h3", text: "5. Le CTA Like Justifié" },
      { type: "p", text: "Demander un like sans raison ne fonctionne pas. Donner une raison émotionnelle ou logique décuple le taux de réponse." },
      { type: "example", title: "Formules qui marchent", text: "\"Like si ça t'a appris quelque chose.\"\n\"Un like = tu m'aides à toucher plus de gens avec ce message.\"\n\"Si t'es d'accord avec ça, like la vidéo.\"" },
      { type: "h2", text: "Où placer ton CTA dans la vidéo ?" },
      { type: "stats", items: [
        { label: "Début (0-3s) — Mauvais", value: "❌", color: "#ef4444" },
        { label: "Milieu — Risqué", value: "⚠️", color: "#FDB51A" },
        { label: "Fin naturelle — Optimal", value: "✅", color: "#22c55e" },
        { label: "Après le reveal — Parfait", value: "🔥", color: "#FF1654" },
      ]},
      { type: "p", text: "Le meilleur moment pour placer un CTA c'est juste après avoir délivré la valeur promise — quand l'émotion est au maximum et que le viewer est le plus réceptif. Jamais en début de vidéo (trop tôt, pas encore de confiance) et rarement au milieu (interrompt le flow)." },
      { type: "h2", text: "La règle des CTAs multiples" },
      { type: "p", text: "Ne place jamais plus de 2 CTAs dans une vidéo. Si tu demandes trop d'actions à la fois, l'audience ne fait rien — c'est la paralysie du choix. Choisis le CTA le plus adapté à l'objectif de la vidéo." },
      { type: "ul", items: [
        "Vidéo éducative / tutoriel → CTA Sauvegarde (valeur durable)",
        "Contenu divertissant → CTA Partage (\"envoie à un ami\")",
        "Contenu de niche → CTA Abonnement avec promesse",
        "Contenu débat → CTA Commentaire avec question",
      ]},
      { type: "h2", text: "Le timing du CTA à l'oral vs à l'écrit" },
      { type: "p", text: "Sur TikTok, tu peux utiliser le CTA de deux façons : à l'oral (tu le dis dans la vidéo) ou à l'écrit (overlay de texte). Les deux se renforcent. L'idéal est de combiner les deux — dis le CTA à l'oral ET affiche-le en texte simultanément." },
      { type: "tip", label: "💡 Pro Tip", text: "Analyse les vidéos qui ont le meilleur taux de commentaires et de sauvegardes dans ta niche avec NicheAnalyze. Tu verras exactement quels CTAs utilisent tes concurrents les plus performants — et tu pourras les adapter à ton style." },
      { type: "h2", text: "Conclusion" },
      { type: "p", text: "Un bon CTA ne se sent pas comme une demande — il se sent comme une invitation naturelle. Sois spécifique, donne une raison, place-le au bon moment, et n'en mets qu'un ou deux par vidéo. C'est la différence entre une vidéo qui fait des vues et une vidéo qui fait grandir ton compte." },
    ],
  },
];

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(current: BlogPost, count = 3): BlogPost[] {
  return blogPosts
    .filter((p) => p.slug !== current.slug && (p.niche === current.niche || p.category === current.category))
    .slice(0, count);
}
